services:
  - type: web
    name: topo-smart-parser-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: topo-smart-parser-frontend
    env: python
    plan: free
    rootDir: frontend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: API_URL
        fromService:
          name: topo-smart-parser-backend
          type: web
          property: url
      - key: PORT
        value: 8050
